version: '3'
services:
  web:
    build: .
    volumes:
      - ./express-app:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
volumes:
  db-volume:
